version: '1.0'
services:
  scooby_api:
    image: scooby_api
    container_name: scoobyapi
    build:
      context: .
      dockerfile: ScoobyRelationshipAPI/Dockerfile
    restart: on-failure      
    ports:
      - 5003:8003
    depends_on:
      - scoob_db
    networks:
      - scoob_network

  scooby_webapp:
    image: scooby_webapp
    container_name: scoobywebapp
    build:
      context: .
      dockerfile: ScoobWebApp/Dockerfile
    restart: on-failure      
    ports:
      - 5002:8002
    depends_on: 
      - scooby_api
    networks: 
      - scoob_network
      
  scoob_db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Password123"
      ACCEPT_EULA: "Y"
    container_name: scoobsqlserver
    hostname: scoobsqlserver
    ports:
      - "1443:1433"
    networks: 
      - scoob_network

  scoob_test:
    image: scoob_test
    container_name: scoobtest
    build:
      context: .
      dockerfile: ScoobTestBDD/Dockerfile
    restart: on-failure      
    depends_on: 
      - scooby_api
      - selenium-hub
    environment:
      - ASPNETCORE_ENVIRONMENT=remote
    networks:
      - scoob_network

  scoob_int_test:
    image: scoob_int_test
    container_name: scoobintegrationtest
    build:
      context: .
      dockerfile: ScoobIntegrationTest/Dockerfile
    networks:
      - scoob_network

  node-docker:
    image: selenium/node-docker:4.8.0-20230210
    volumes:
      - ./assets:/opt/selenium/assets
      - ./GridConfig/config.toml:/opt/bin/config.toml
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - scoob_network

  selenium-hub:
    image: selenium/hub:4.8.0-20230210
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    networks:
      - scoob_network

networks: 
   scoob_network: